### ISSUE TITLE
No npm package called @miniprogram-i18n/gulp-locales-loader @miniprogram-i18n/gulp-wxml-transformer

### ISSUE THREAD

**Issue by lubancafe** [wechat-miniprogram/miniprogram-i18n#1]
In Readme, @miniprogram-i18n/gulp-locales-loader @miniprogram-i18n/gulp-wxml-transformer are needed to be installed. 

However, no such packages in npm registry. Where are they?

------------------ Console Error ---------------------
$ npm i -D @miniprogram-i18n/gulp-locales-loader @miniprogram-i18n/gulp-wxml-transformer
× Install fail! Error: GET https://registry.npm.taobao.org/@miniprogram-i18n%2Fgulp-locales-loader response 404 status
Error: GET https://registry.npm.taobao.org/@miniprogram-i18n%2Fgulp-locales-loader response 404 status

**Comment by ele828** [comment]
It's been published now!
```
npm i -D gulp @miniprogram-i18n/gulp-i18n-locales @miniprogram-i18n/gulp-i18n-wxml
```
