### ISSUE TITLE
按文档说明步骤走，无法实现demo可视化效果？

### ISSUE THREAD

**Issue by weizuichunsun** [wechat-miniprogram/miniprogram-i18n#10]
![image](https://user-images.githubusercontent.com/27394381/68753077-57904380-063f-11ea-876e-3d7d588deca2.png)

i18n文本定义
miniprogram-i18n 目前采用 JSON 文件对 i18n 文本进行定义。使用之前，需要在项目源文件下新建 i18n 目录。

目录结构如下：

我按照官方文档和GitHub 步骤走，始终无法构建成功的demo，期望得到解决

**Comment by h4091** [comment]
执行完
`npm i -D gulp @miniprogram-i18n/gulp-i18n-locales @miniprogram-i18n/gulp-i18n-wxml
npm i -S @miniprogram-i18n/core`
这两行命令执行后，要在微信开发者工具中点击“工具”->"构建npm"

**Comment by ele828** [comment]
可以参考下 examples https://github.com/wechat-miniprogram/miniprogram-i18n/blob/master/examples/README.md
