### ISSUE TITLE
使用了examples中的demo 打包后在wxml中使用文本插值无效

### ISSUE THREAD

**Issue by jj56313751** [wechat-miniprogram/miniprogram-i18n#11]
![图片](https://user-images.githubusercontent.com/12592156/69300385-05a67980-0c4e-11ea-8f6f-a3c8acd481e4.png)

**Comment by ele828** [comment]
已经修复了。重新安装一下 @miniprogram-i18n/gulp-i18n-locales ，注意版本需要是 rc7。
