### ISSUE TITLE
@miniprogram-i18n/gulp-i18n-wxml编译错误，

### ISSUE THREAD

**Issue by lou920217** [wechat-miniprogram/miniprogram-i18n#14]
![image](https://user-images.githubusercontent.com/5370271/72053434-fe245800-3301-11ea-8228-d18d45d795c1.png)

如图，当wxml中有 其他 wxs 并且wxs 中有 <> 运算符的时候报错

**Comment by ele828** [comment]
这个问题已经修复了，安装最新版再试试看

**Comment by gaterking** [comment]
1.0.0-rc.7 @ele828  依然有问题

**Comment by gaterking** [comment]
@ele828 淘宝源、tnpm没有1.0.0.rc8
