### ISSUE TITLE
JSON文件添加新的单次字段后，编译dist 预览，JS文件调用新的字段需要重新构建npm？ 

### ISSUE THREAD

**Issue by weizuichunsun** [wechat-miniprogram/miniprogram-i18n#17]
JSON文件添加新的单次字段后，编译dist 预览，JS文件调用新的字段需要重新构建npm？ 

例如 en.json =  { a:1 } 

src 手动更新  en.json =  { a:1 , b:2 }  重新编译 dist 文件

dist 文件无法调用  字段 b，， i18n.t("b")  

需在开发工具中 点击构建，才能正常显示    i18n.t("b")   为2 ，而不是 b ，是否必须这样操作呢？
![image](https://user-images.githubusercontent.com/27394381/75745826-69fbcd80-5d53-11ea-8044-85a87c69bda5.png)

**Comment by ele828** [comment]
不用在工具重新点击构建，只需要把小程序代码重新编译一下即可。
