### ISSUE TITLE
在page使用I18nPage 报错

### ISSUE THREAD

**Issue by songStar0904** [wechat-miniprogram/miniprogram-i18n#2]
thirdScriptError 
 sdk uncaught third Error 
 [i18n] ensure run initI18n() in app.js before using I18n library 
 Error: [i18n] ensure run initI18n() in app.js before using I18n library
![image](https://user-images.githubusercontent.com/21984603/56706229-c9a64700-6746-11e9-81b7-ee44bb4687ff.png)
是不是因为没有构建？ 其他步骤都安照快速入门来的。

**Comment by songStar0904** [comment]
是没有构建的问题  所以使用这个工具在开发中要怎么调试呢 还是只能构建后才能用开发者工具调试。。。

**Comment by ele828** [comment]
需要在 app.js 调用一下 initI18n 来加载你的翻译文件。默认会从 `../../../i18n/locales.js` 路径里加载。具体可以参考一下 examples，本地跑一下试试。
```js
import {initI18n} from '@miniprogram-i18n/core';

initI18n('../locales.js');    // locales 文件路径
```

**Comment by jxZhangLi** [comment]
@songStar0904   locales.js  怎么配置的？文档 ，例子中都没写

**Comment by xiaofang11** [comment]
遇到了一样的错误。同问locales.js 怎么配置的
