### ISSUE TITLE
locales.js 配置

### ISSUE THREAD

**Issue by jxZhangLi** [wechat-miniprogram/miniprogram-i18n#3]
![image](https://user-images.githubusercontent.com/16809535/57667787-7e8d9e80-7637-11e9-8c8d-3c5cff3b6a71.png)

locales.js 是用来干嘛的啊，文档中没写明，examples 也没有，不理解

**Comment by ele828** [comment]
locales.js 是 gulp-i18n-locales 自动生成的语言文本文件，具体可以参考文档：https://github.com/wechat-miniprogram/miniprogram-i18n/blob/master/docs/gulp.md#gulp-i18n-locales-%E9%85%8D%E7%BD%AE
