### ISSUE TITLE
开发的时候是在src内开发还是在dist里开发

### ISSUE THREAD

**Issue by Jingjingsixgod** [wechat-miniprogram/miniprogram-i18n#30]
开发的时候是在src内开发还是在dist里开发

**Comment by leonyangdev** [comment]
> 开发的时候是在src内开发还是在dist里开发

都可以。

1、src 里面开发，保存之后需要重编译，再次生成 dist

2、src 里面一次性编译好，将 dist 作为以后的开发目录，只维护 dist 里面 i18n 的语言配置
