### ISSUE TITLE
有一个小问题，需要帮忙看一下

### ISSUE THREAD

**Issue by const-undefined-man** [wechat-miniprogram/miniprogram-i18n#31]
项目里面引用了vant UI组件库，然后build之后，报错了

i18n会在使用的组件里面也添加上i18n的引用代码，请问 这个 怎么去掉呢

请看图片
<img width="473" alt="image" src="https://user-images.githubusercontent.com/3367457/155889892-7696d3e6-40d8-42d0-80d7-451cc93b5c59.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/3367457/155889893-1ce02e94-4006-4b07-a22e-ff30d6c3e6f6.png">
<img width="708" alt="image" src="https://user-images.githubusercontent.com/3367457/155889919-fb0b39bc-f30f-4483-b63f-d9c524ce88ac.png">

**Comment by leonyangdev** [comment]
> 项目里面引用了vant UI组件库，然后build之后，报错了
> 
> i18n会在使用的组件里面也添加上i18n的引用代码，请问 这个 怎么去掉呢
> 
> 请看图片 <img alt="image" width="473" src="https://user-images.githubusercontent.com/3367457/155889892-7696d3e6-40d8-42d0-80d7-451cc93b5c59.png"> <img alt="image" width="416" src="https://user-images.githubusercontent.com/3367457/155889893-1ce02e94-4006-4b07-a22e-ff30d6c3e6f6.png"> <img alt="image" width="708" src="https://user-images.githubusercontent.com/3367457/155889919-fb0b39bc-f30f-4483-b63f-d9c524ce88ac.png">

gulpfile.js 文件这么写

```js
function transpileWxml() {
  return src([
    "src/**/*.wxml",
    "!src/miniprogram_npm/",
  ]).pipe(gulpI18nWxml()).pipe(dest("miniprogram/"));
}
```

并且 src 目录下不要 构建 npm，请在 dist 里面进行构建 npm
