### ISSUE TITLE
Windows下会导致合并后wxml报错：找不到locales.wxs文件

### ISSUE THREAD

**Issue by h4091** [wechat-miniprogram/miniprogram-i18n#6]
wo现在的解决方法是修改下面的文件：
在项目根目录打开“node_modules\@miniprogram-i18n\gulp-i18n-wxml”文件夹，打开index.js文件，找到如下代码：
`var relativeWxsPath = path.relative(path.dirname(file.path), wxsPath);`
在其后添加如下代码并保存：
`relativeWxsPath = relativeWxsPath.replace(/\\/g, '/');`
修改后代码如下：
```
var transformedContents = transfomer.transform(file.contents.toString('utf-8'));
var relativeWxsPath = path.relative(path.dirname(file.path), wxsPath);
relativeWxsPath = relativeWxsPath.replace(/\\/g, '/');
var wxsTag = getWxsTag(relativeWxsPath, wxsModuleName);
file.contents = Buffer.concat([Buffer.from(wxsTag), Buffer.from(transformedContents)]);
```

**Comment by mela93** [comment]
一样遇到了这个坑……同事Windows下遇到了这个问题……

**Comment by mela93** [comment]
对了我是一百年开发一边国际化重复gulp之后就变成这样了
![image](https://user-images.githubusercontent.com/17722672/64667366-2b641500-d48c-11e9-8f4c-d24165af9a5e.png)

**Comment by mit-lang-wang** [comment]
Workaround on Windows: 
1.  go to node_modules\@miniprogram-i18n\gulp-i18n-wxml
2.  eidit index.jx, replace `path$$1` with 'path$$1.replace(/\\/g,'/') '
 ```typescript
var getWxsTag = function (path$$1, moduleName) { return "<wxs src=\"" + path$$1.replace(/\\/g,'/') + "\" module=\"" + moduleName + "\" />\n"; };
```
3. Build npm on Wechat Miniprogram Developer  IDE

**Comment by lovelangy** [comment]
Workaround on Windows:
1. go to 'node_modules\@miniprogram-i18n\gulp-i18n-wxml'
2. edit index.js, replace `path$$$1' with `path$$1.replace(/\\/g,'/')`
```typescript
var getWxsTag = function (path$$1, moduleName) { return "<wxs src=\"" + path$$1.replace(/\\/g,'/') + "\" module=\"" + moduleName + "\" />\n"; };
```
3, Build NPM on Wechat Developer Tool to generate new 'miniprogram_npm' packages

**Comment by ele828** [comment]
已经修复了，可以升级 @miniprogram-i18n/gulp-i18n-wxml  到 rc7 或以上版本。
