### ISSUE TITLE
app.js 引入包，直接报错，怎么处理？

### ISSUE THREAD

**Issue by weizuichunsun** [wechat-miniprogram/miniprogram-i18n#9]
app.js 引入包，直接报错，怎么处理？
![image](https://user-images.githubusercontent.com/27394381/68752743-cb7e1c00-063e-11ea-8b5c-876c19b373c8.png)

**Comment by ele828** [comment]
在开发者工具里需要点一下 “工具” -> "构建 npm"。如果是 examples 项目可以参考下文档：https://github.com/wechat-miniprogram/miniprogram-i18n/blob/master/examples/README.md
